version: '3.7'
services:
  postgresql:
    image: postgres:13.9
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=public
      - PGDATA=/opt/postgresql/
    ports:
      - "5432:5432"